//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenSkyCrmEntities : DbContext
    {
        public OpenSkyCrmEntities()
            : base("name=OpenSkyCrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<os_articles> os_articles { get; set; }
        public virtual DbSet<os_articles_categories> os_articles_categories { get; set; }
        public virtual DbSet<os_city> os_city { get; set; }
        public virtual DbSet<os_customers> os_customers { get; set; }
        public virtual DbSet<os_document_type> os_document_type { get; set; }
        public virtual DbSet<os_invoices_detail> os_invoices_detail { get; set; }
        public virtual DbSet<os_iva> os_iva { get; set; }
        public virtual DbSet<os_timbrado_data> os_timbrado_data { get; set; }
        public virtual DbSet<os_sales_conditions> os_sales_conditions { get; set; }
        public virtual DbSet<os_currency_type> os_currency_type { get; set; }
        public virtual DbSet<os_invoices_header> os_invoices_header { get; set; }
        public virtual DbSet<os_payments> os_payments { get; set; }
        public virtual DbSet<os_payment_types> os_payment_types { get; set; }
    }
}
