//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_articles
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CategorieId { get; set; }
        public string ReferenceInternal { get; set; }
        public Nullable<int> InitialAmount { get; set; }
        public Nullable<int> CurrentAmount { get; set; }
        public Nullable<int> MinimumAmount { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.Guid> IvaId { get; set; }
        public Nullable<System.Guid> UserCreated { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UserUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Status { get; set; }
    
        public virtual os_articles_categories os_articles_categories { get; set; }
        public virtual os_iva os_iva { get; set; }
    }
}
