//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_payments
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> InvoiceHeaderId { get; set; }
        public string PaymentTypeId { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> Change { get; set; }
        public string VoucherNumber { get; set; }
    
        public virtual os_invoices_header os_invoices_header { get; set; }
        public virtual os_payment_types os_payment_types { get; set; }
    }
}
