//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public os_person()
        {
            this.os_user = new HashSet<os_user>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AreaId { get; set; }
        public Nullable<System.Guid> ChargesId { get; set; }
        public Nullable<System.Guid> BranchCompanyId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FirstLastName { get; set; }
        public string SecondLastName { get; set; }
        public string Document { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UsuCreated { get; set; }
        public string Status { get; set; }
    
        public virtual os_areas os_areas { get; set; }
        public virtual os_charges os_charges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<os_user> os_user { get; set; }
        public virtual os_branch_company os_branch_company { get; set; }
    }
}
