//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_timbrado_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public os_timbrado_data()
        {
            this.os_invoices_header = new HashSet<os_invoices_header>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> BranchCompanyId { get; set; }
        public string Timbrado { get; set; }
        public Nullable<int> StartRangeTimbrado { get; set; }
        public Nullable<int> EndRangeTimbrado { get; set; }
        public Nullable<System.DateTime> StartDateValidityTimbrado { get; set; }
        public Nullable<System.DateTime> EndDateValidityTimbrado { get; set; }
        public string InvoicesPuntoExpedicion { get; set; }
        public string InvoicesPuntoEstablecimiento { get; set; }
        public Nullable<System.Guid> UserCreatedId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UserUpdateId { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<os_invoices_header> os_invoices_header { get; set; }
    }
}
