//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSky.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenSkySecurityEntities : DbContext
    {
        public OpenSkySecurityEntities()
            : base("name=OpenSkySecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<os_areas> os_areas { get; set; }
        public virtual DbSet<os_charges> os_charges { get; set; }
        public virtual DbSet<os_person> os_person { get; set; }
        public virtual DbSet<os_profiles> os_profiles { get; set; }
        public virtual DbSet<os_status> os_status { get; set; }
        public virtual DbSet<os_user> os_user { get; set; }
        public virtual DbSet<os_branch_company> os_branch_company { get; set; }
    }
}
